// Short invitations, never automatic navigation. Context and recent lines guide delivery.
const p=(text,topic='help')=>({text,topic});
export const prompts=Object.freeze({
 GENERAL:[p('You can open things here.'),p('A little curiosity goes a long way.'),p('I brought my own chair.','chair'),p('Yes, that is a working chair.','chair'),p('I’ll be here, investigating.'),p('The details are worth a look.','projects'),p('There’s a human behind this.','study'),p('Take the scenic route.','fun'),p('A good question beats a quick answer.'),p('Browse at your own speed.'),p('I’m stretching. Carry on.','chair'),p('A tiny desk job.','chair'),p('A shortcut, if you need one.','help'),p('Code has a backstory.','source'),p('A click is a reasonable hypothesis.','projects'),p('I have a few suggestions.','help'),p('No rush. I’ve got a chair.','chair'),p('That deserves a closer look.','projects'),p('The next door is yours.','help'),p('I promise the links do things.','help'),p('Curiosity looks good on you.','secrets'),p('One small detour?','fun'),p('A map of the site, minus the legend.','help'),p('Something catch your eye?','best'),p('I’m the small one. Ahmed writes back.','contact'),p('You’ve got options.','help'),p('There’s more than the first impression.','projects'),p('I can point. You get to choose.','help')],
 ENTRY:[p('Start with a project.','best'),p('The shelf is not just decoration.','worlds'),p('One door for work. One for play.','break'),p('Maps or interfaces?','build'),p('Three views. Same curious person.','worlds'),p('Try the other entrance.','worlds'),p('The little workbench has things to say.','build'),p('A portfolio with a side quest.','fun'),p('The serious work is one click away.','projects'),p('Need the quick tour?','help'),p('I’ll handle the pacing.','chair'),p('The projects are better at introductions.','best'),p('There’s a game on that shelf.','reversi'),p('Welcome to the rabbit hole.','secrets')],
 WORKBENCH:[p('Want to see the moving parts?','stack'),p('Different jobs, different tools.','stack'),p('The database has entered the chat.','databases'),p('An API is a conversation with rules.','integrations'),p('Follow the data, then check it.','data'),p('The bug rarely introduces itself.','testing'),p('Interfaces are only half the story.','backend'),p('Maps live on this workbench too.','gistools'),p('A passing test is a useful start.','testing'),p('Good integration makes fewer headlines.','cloud'),p('Open a tool. There’s context inside.','stack'),p('Sometimes the answer is a better query.','sql')],
 PORTFOLIO:[p('The stack is inside the project.','stack'),p('The contribution matters as much as the tools.','contributions'),p('The next card tells a different story.','projects'),p('One project can’t explain all of it.','best'),p('There’s source where it can be shared.','source'),p('That card has a second layer.','projects'),p('The archive remembers.','old'),p('Try a project outside your usual lane.','best')],
 TRUSTAI:[p('Confident answers still need checking.','llmchecks'),p('A risk signal is not a verdict.','ai'),p('The model doesn’t get the last word.','llmchecks'),p('Compare the answer, not the swagger.','llmchecks'),p('A team built this. Roles matter.','contributions'),p('The live app is there to explore.','trustai'),p('What happens after the model answers?','truststack'),p('The limitations are part of the story.','trustai')],
 GIS:[p('You found the spatial side.','gis'),p('Location is doing some heavy lifting.','garden'),p('A map needs more than a nice color.','gistools'),p('Coordinates: tiny numbers, large consequences.','gis'),p('The shortest route isn’t always accessible.','gis'),p('The legend deserves a little respect.','gis'),p('A garden starts with the right place.','garden'),p('Maps turn a table into a question.','data')],
 ABOUT:[p('Code and maps were both in the picture.','study'),p('A little context for the person.','experience'),p('The degree is only part of the story.','masters'),p('The work history has another layer.','experience'),p('There’s a life away from the keyboard.','photo'),p('From spatial data to software.','study'),p('Ask about the path between projects.','experience')],
 RESUME:[p('The formal version, all in one place.','resume'),p('Need a copy for later?','resume'),p('A role worth talking about?','available')],
 CONTACT:[p('This is the part with the real inbox.','contact'),p('Good conversations start small.','contact'),p('A team, a project, a question?','available'),p('GitHub has the source.','source'),p('LinkedIn has the professional chapter.','experience'),p('You’ve looked around. Say hello.','contact'),p('I point. Ahmed answers.','contact')],
 SIDE_QUESTS:[p('The corners are worth watching.','reversi'),p('One move can change the board.','reversi'),p('This Reversi is the newer one.','reversi'),p('The old Java project has its own page.','contributions'),p('A small puzzle, a short break.','fun'),p('There’s no timer on curiosity.','break'),p('A detour counts as exploring.','secrets'),p('Look two moves ahead.','reversi')],
 VISUALS:[p('Some things are better through a lens.','photo'),p('Still choosing what belongs in this room.','visuals'),p('Composition is a kind of debugging.','photo'),p('Not every experiment starts with code.','visuals')],
 FOOTER:[p('You made it to the small print.','secrets'),p('The end of the page isn’t the last door.','old'),p('Back for another look?','best'),p('One more game before you go?','reversi')],
 LOST:[p('This route needs recalculating.','lost'),p('A dead end with a helpful guide.','lost'),p('Let’s get you somewhere useful.','lost')],
 GDSC:[p('Six people. One shared application.','gdsc'),p('Login is a feature, not a footnote.','gdsc'),p('Google’s student-club chapter is the context.','gdsc'),p('The portal has roles of its own.','gdsc'),p('There’s a sprint story behind this one.','gdsc'),p('The repository keeps the team history.','source')]
});
export function bank(context){return [...(prompts[context]||prompts.ENTRY).map(x=>({...x,contextual:true})),...prompts.GENERAL]}
