import {initial,legal,move,score} from './reversi-engine.mjs';
const name=p=>p===1?'Dark':'Light',coord=i=>String.fromCharCode(65+i%8)+(Math.floor(i/8)+1);
const element=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e};
export function mountReversi(host){let state=initial(),history=[],focus=19,hints=true,timer;const wrap=element('div','reversi'),scores=element('div','game-scores'),status=element('p','game-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');const board=element('div','reversi-board');board.setAttribute('role','grid');board.setAttribute('aria-label','Reversi board. Use arrow keys to move; Enter or Space to place a disc.');board.setAttribute('aria-rowcount','8');board.setAttribute('aria-colcount','8');
 const squares=[];for(let r=0;r<8;r++){const row=element('div','board-row');row.setAttribute('role','row');for(let c=0;c<8;c++){const i=r*8+c,cell=element('div','board-cell'),b=element('button','board-square');cell.setAttribute('role','gridcell');b.type='button';b.dataset.square=i;b.addEventListener('click',()=>play(i));b.addEventListener('keydown',e=>{let next=i;if(e.key==='ArrowRight')next=r*8+(c+1)%8;else if(e.key==='ArrowLeft')next=r*8+(c+7)%8;else if(e.key==='ArrowDown')next=((r+1)%8)*8+c;else if(e.key==='ArrowUp')next=((r+7)%8)*8+c;else if(e.key==='Home')next=e.ctrlKey?0:r*8;else if(e.key==='End')next=e.ctrlKey?63:r*8+7;else return;e.preventDefault();e.stopPropagation();setFocus(next,true)});cell.append(b);row.append(cell);squares.push(b)}board.append(row)}
 const controls=element('div','game-controls'),undo=element('button',null,'Undo'),reset=element('button',null,'New game'),hint=element('button',null,'Move hints');[undo,reset,hint].forEach(b=>{b.type='button';controls.append(b)});hint.setAttribute('aria-pressed','true');undo.addEventListener('click',()=>{if(history.length){state=history.pop();focus=state.last??19;render();setFocus(focus,true)}});reset.addEventListener('click',()=>{state=initial();history=[];focus=19;render()});hint.addEventListener('click',()=>{hints=!hints;hint.setAttribute('aria-pressed',String(hints));render()});
 const help=element('details','game-help'),summary=element('summary',null,'How to play'),rules=element('p',null,'Two players share this screen. Dark moves first. Place a disc to bracket a straight line of opposing discs between your new disc and an existing one. All bracketed discs flip. You must play a legal move; a turn passes automatically only when there is no move. When neither player can move, the larger count wins.');help.append(summary,rules);const keys=element('p',null,'Arrow keys move around the board. Home and End move across a row; Ctrl+Home and Ctrl+End reach the corners. Enter or Space places a disc. Escape closes the panel.');help.append(keys);const provenance=element('small','game-provenance','New for this site. Separate from the 2022 Java coursework. '),archive=element('a',null,'Historical source and credits');archive.href='/case-studies/othello/';provenance.append(archive);wrap.append(scores,status,board,controls,help,provenance);host.append(wrap);
 function setFocus(i,moveFocus=false){focus=i;squares.forEach((b,j)=>b.tabIndex=j===i?0:-1);if(moveFocus)squares[i].focus({preventScroll:true})}
 function render(flips=[]){const available=legal(state.board,state.turn),counts=score(state.board);scores.replaceChildren(...[1,2].map(p=>{const e=element('span'),dot=element('i','score-dot score-'+(p===1?'dark':'light'));dot.setAttribute('aria-hidden','true');e.append(dot,document.createTextNode(name(p)+' '+(p===1?counts.dark:counts.light)));return e}));status.textContent=state.over?(counts.dark===counts.light?'A draw. A very diplomatic board.':(counts.dark>counts.light?'Dark':'Light')+' wins. '+counts.dark+'–'+counts.light+'.'):(state.passed?name(state.passed)+' has no move. ':'')+name(state.turn)+' to move. '+available.length+' legal '+(available.length===1?'square.':'squares.');squares.forEach((b,i)=>{const value=state.board[i],can=available.includes(i)&&!state.over;b.replaceChildren();if(value){const disc=element('span','board-piece piece-'+(value===1?'dark':'light'));disc.setAttribute('aria-hidden','true');b.append(disc)}b.dataset.legal=String(can);b.dataset.hideHints=String(!hints);b.setAttribute('aria-disabled',String(!can));b.setAttribute('aria-label',coord(i)+': '+(value?name(value)+' disc':can?'empty, legal move for '+name(state.turn):'empty, no legal move'));b.classList.toggle('is-flipped',flips.includes(i))});setFocus(focus);undo.disabled=!history.length;clearTimeout(timer);timer=setTimeout(()=>squares.forEach(b=>b.classList.remove('is-flipped')),200);wrap.dataset.moves=history.length;wrap.dataset.turn=state.turn;wrap.dataset.over=String(state.over)}
 function play(i){const next=move(state,i);setFocus(i);if(!next){status.textContent=state.over?'This game is finished. Start a new one when you’re ready.':coord(i)+' is not a legal move. '+name(state.turn)+' still to move.';return}history.push(state);state=next;render(next.flipped)}render();return ()=>clearTimeout(timer);
}
export function mountSignal(host){let expected=0;const intro=element('p',null,'Give the signal a path: source → process → output. The order matters.'),rack=element('div','signal-puzzle'),feedback=element('p','signal-state','Start at the source.');feedback.setAttribute('role','status');const buttons=[];for(const [i,label] of ['Source','Process','Output'].entries()){const b=element('button','signal-switch',label);b.type='button';b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>{if(expected===3){feedback.textContent='The signal is through. Reset for another go.';return}if(i!==expected){expected=0;buttons.forEach(x=>x.setAttribute('aria-pressed','false'));feedback.textContent='That wire goes nowhere yet. Start at the source.';return}b.setAttribute('aria-pressed','true');expected++;feedback.textContent=expected===3?'Signal through. Three clicks, zero cloud bills.':expected===1?'Source ready. Give it a process.':'Processed. Send it to the output.'});buttons.push(b);rack.append(b)}const controls=element('div','game-controls'),reset=element('button',null,'Reset the path');reset.type='button';reset.addEventListener('click',()=>{expected=0;buttons.forEach(b=>b.setAttribute('aria-pressed','false'));feedback.textContent='Start at the source.'});controls.append(reset);host.append(intro,rack,feedback,controls,element('p','signal-note','A new local interface experiment. No account, network or scorekeeping.'));return ()=>{};
}
