'use strict';
(() => {
const root=document.documentElement,reduce=matchMedia('(prefers-reduced-motion:reduce)'),narrow=matchMedia('(max-width:900px)'),menu=document.querySelector('.menu-icon'),links=document.querySelector('.nav-links'),theme=document.getElementById('toggle-dark-mode');
const reduced=()=>reduce.matches||root.dataset.motion==='reduce';
function closeMenu(returnFocus=false){links.classList.remove('active');links.inert=narrow.matches;menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');if(returnFocus)menu.focus()}
closeMenu();menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';links.classList.toggle('active',open);links.inert=narrow.matches&&!open;menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation')});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true')closeMenu(true)});
for(const type of ['click','focusin'])document.addEventListener(type,e=>{if(!e.target.closest('header'))closeMenu()});
narrow.addEventListener('change',()=>closeMenu());links.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>closeMenu()));
function applyTheme(save=false){const night=theme.checked;root.dataset.theme=night?'night':'day';document.body.classList.toggle('dark-mode',night);document.querySelector('meta[name=theme-color]').content=getComputedStyle(root).getPropertyValue('--canvas').trim();if(save)try{localStorage.setItem('mandalaw-theme',root.dataset.theme)}catch{}root.dataset.themeTransition='true';clearTimeout(applyTheme.timer);applyTheme.timer=setTimeout(()=>root.dataset.themeTransition='false',reduced()?0:340)}
theme.checked=root.dataset.theme==='night';applyTheme();theme.addEventListener('change',()=>applyTheme(true));root.classList.remove('theme-initializing');
const sections=[...document.querySelectorAll('main>section')];
// One-time entrances: content remains visible if JS fails. Child layers never gate access.
let running=[];root.dataset.entranceState='ready';function reveal(section){if(section.dataset.revealed==='true')return;section.dataset.revealed='true';if(reduced())return;root.dataset.entranceState='running';const items=section.id==='about'?[section.querySelector('h1'),section.querySelector('#about-picture'),section.querySelector('p')]:section.id==='portfolio'?[section.querySelector('h2'),section.querySelector('.showcase-stage'),section.querySelector('.project-rail'),section.querySelector('.deck-wayfinding')]:section.id==='contact'?[section.querySelector('h2'),section.querySelector('.contact-letter'),section.querySelector('.contact-content>p'),section.querySelector('.contact-badges')]:[section.querySelector('h2'),...section.querySelectorAll('.service,blockquote')];const style=root.dataset.entrance,dist=style==='quiet'?6:style==='depth'?18:12,duration=style==='quiet'?360:style==='depth'?620:520;items.filter(Boolean).forEach((el,i)=>{const frames=[{opacity:.2,translate:`0 ${dist}px`,...(style==='depth'?{filter:'blur(2px)'}:{})},{opacity:1,translate:'0 0',...(style==='depth'?{filter:'blur(0px)'}:{})}];const a=el.animate(frames,{duration,delay:i*65,easing:'cubic-bezier(.2,.75,.25,1)',fill:'backwards'});running.push(a);a.finished.catch(()=>{}).finally(()=>{running=running.filter(item=>item!==a);if(!running.length)root.dataset.entranceState='ready'})})}
document.addEventListener('section-reveal',e=>reveal(e.detail.section));
const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting&&document.documentElement.dataset.scrollState!=='TRANSITIONING'){reveal(e.target);observer.unobserve(e.target)}})},{rootMargin:'0px 0px -10% 0px',threshold:0.08});sections.forEach(s=>observer.observe(s));reduce.addEventListener('change',()=>{if(reduced())running.forEach(a=>a.cancel())});
})();

// Final palette is available before initial browser chrome is updated.
addEventListener('load',()=>{const root=document.documentElement;document.querySelector('meta[name=theme-color]').content=getComputedStyle(root).getPropertyValue('--canvas').trim();root.dataset.materialReady=String(getComputedStyle(root).getPropertyValue('--material-system').trim()==='pass8');root.dataset.initialSection=location.hash.slice(1)||'about'});
